### ISSUE TITLE
[BUG] Error Forge 1.20.4

### ISSUE THREAD

**Issue by Dilen0001** [Vera-Firefly/Pojav-Glow-Worm#161]
### Describe the bug

Forge 1.20.4 Exit Code 1 While Playing

### The log file and images/videos

[latestlog.txt](https://github.com/Vera-Firefly/Pojav-Glow-Worm/files/14567818/latestlog.txt)

### Steps To Reproduce

```markdown
Install Forge 1.20.4
```

### Platform

```markdown
- Device model: Vivo V23e
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: Edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?
There isn't any

**Comment by Vera-Firefly** [comment]
try update your launcher

**Comment by Vera-Firefly** [comment]
https://github.com/Vera-Firefly/Pojav-Glow-Worm/actions/runs/8508215479
