### ISSUE TITLE
LOGIN ERROR [BUG] <Short description>

### ISSUE THREAD

**Issue by Shomai123** [Vera-Firefly/Pojav-Glow-Worm#185]
### Describe the bug

I can't login on POJAVLUNCHER, I don't know why, PLEASE fix it immediately!!

### The log file and images/videos

![Screenshot_2024-04-04-19-54-42-56_405a2fc07b254ef5ee3229f4fec175cf](https://github.com/Vera-Firefly/Pojav-Glow-Worm/assets/165415539/c1a7be88-a914-4fe9-a1b8-ea832ed17c80)

### Steps To Reproduce

```markdown
FIX IT IMMEDIATELY!!
```

### Expected Behavior

I THOUGHT EVERYTHING IS OKAY BUT I'M DISAPPOINTED TO THIS ISSUE

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version
```

**Comment by ZiMeng-Firefly** [comment]
Check your Internet connection
