### ISSUE TITLE
[QUESTION] where thiz launxher is made in android studio or intelij idea or vscode??

### ISSUE THREAD

**Issue by Bludose** [Vera-Firefly/Pojav-Glow-Worm#255]
### Describe the bug

tell me where this made jn 

### The log file and images/videos

e

### Steps To Reproduce

```markdown
bludo
```

### Expected Behavior

idk

### Platform

```markdown
- Device model: V2249
- CPU architecture: ARM
- Android version: 14
- PojavLauncher version: Latdst
```

**Comment by Vera-Firefly** [comment]
Wait, what are you trying to say? There's something wrong with your description.
